### ISSUE TITLE
Sql injection

### ISSUE THREAD

**Issue by YuriiKovalenko** [mokuteki225/nest-shop#8]
https://github.com/mokuteki225/nest-shop/blob/9dea281980e7cb8e3e81b98bc46f29a68cc959f8/src/migrations/1638310459218-RolesData.ts#L6

Нельзя напрямую в строку запроса вставлять значения, для этого есть параметры. Нельзя потому что уязвимость sql injection.

**Comment by vkondratiuk482** [comment]
Values don't depend on user input, so I guess in this case it's not a problem. Thanks for the issue anyways!
