### ISSUE TITLE
Не стоит кидать HttpException из сервиса

### ISSUE THREAD

**Issue by YuriiKovalenko** [mokuteki225/nest-shop#9]
https://github.com/mokuteki225/nest-shop/blob/9dea281980e7cb8e3e81b98bc46f29a68cc959f8/src/user/user.service.ts#L73

Сервис это часть бизнес-логики, он не должен ничего знать о http.
Или делай кастомные ошибки, а в exception filter уже подменяй на HttpException. Или возвращай null, делай проверку в контроллере и из него уже кидай HttpException.

**Comment by vkondratiuk482** [comment]
fixed, thanks!
